spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.106.64.14/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    jdbc:mysql://localhost:3306/csm"+"?serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: F://日志
#  file: F://日志/sell.log
#  level:
#    com.imooc.LoggerTest: debug

# 下面是微信相关的配置
wechat:
#  mpAppId: wxdcf91e9f784bfad0
#  mpAppSecret: c467c06d98a2447f5ddef6ca8f47f268 #测试号appId,appSecret
  mpAppId: wxe2c4567fb58dd5a7
  mpAppSecret: 14028ef0bd7f2982da952e209a5c442a #借用号appId,appSecret
  mpToken: morning
  mpAesKey: n8U4dp9K5eWl4dOp8pBhqSVgGKSWlxHo85yVsw8WMIy
#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #开放平台测试号appId,appSecret
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e #借用帐号appId,appSecret
  mchId: 1520607991
  mchKey: n8U4dp9K5eWl4dOp8pBhqSVgGKSWlxHo
  keyPath: D:/WXCertUtil/cert/1520607991_20190123_cert/apiclient_cert.p12
  notifyUrl: http://yushanfang.online/notify
  templateId:
    orderStatus: GoCullfix05R-rCibvoyI87ZUg50cyieKA5AyX7pPzo

projectUrl:
  wechatMpAuthorize: http://yushanfang.online
  wechatOpenAuthorize: http://yushanfang.online
  sell: http://yushanfang.online
